### ISSUE TITLE
php 8?

### ISSUE THREAD

**Issue by kleijnweb** [paul-thebaud/phpunitgen-console#5]
Wanted to try this out but the composer constraints don't include php 8, several dependencies as well

**Comment by paul-thebaud** [comment]
Hello,
Yes, package is not yet compatible with PHP8 because of some of the dependencies, sorry.
The issue paul-thebaud/phpunitgen-core#6 on the PhpUnitGen core package tracks this.
As soon as dependencies are available, I'll try to make this package compatible.

**Comment by beataburczyk** [comment]
Thank you, tested with Lumen 8.2.1, unfortunately artisan trowing error, In ConsoleServiceProvider.php line 63:Call to a member function delegate() on null, phpunitgen/console 2.0.0-alpha2

**Comment by paul-thebaud** [comment]
Thanks for the feedback @beataburczyk, I'll try to look and fix it soon!

**Comment by paul-thebaud** [comment]
Hi @beataburczyk, I found the problem. There are two issues:
* First inside documentation: the service provider to register is `\PhpUnitGen\Console\Adapters\Laravel\PhpUnitGenServiceProvider::class` (instead of `\PhpUnitGen\Console\Container\ConsoleServiceProvider::class`). Documentation will be fixed on the website when V2 will be released online.
* Second inside console package, where the PhpUnitGenServiceProvider and CommandFinishedListener were only accepting a Laravel application instance. I changed this one to accept both Laravel or Lumen app instance.This is released as `2.0.0-alpha3` and `1.4.0`.
Feel free if you face any other issue, thanks again for the feedback!

**Comment by beataburczyk** [comment]
No luck with 2.0.0-alpha3 too, PHP 8.0.10, the same error like before, if I have chance will check with other fresh Lumen project or Laravel project too. Thanks

**Comment by paul-thebaud** [comment]
Hi @beataburczyk, did you update the register of the service provider inside your `bootstrap/app.php`.
This issue is related to the wrong service provider being registered.

**Comment by beataburczyk** [comment]
Yes, I did 
use PhpUnitGen\Console\Container\ConsoleServiceProvider;

**Comment by paul-thebaud** [comment]
@beataburczyk as specified in my comment, there is an error in documentation, you must use the other one to get it working: `\PhpUnitGen\Console\Adapters\Laravel\PhpUnitGenServiceProvider::class`

**Comment by beataburczyk** [comment]
Apologise, my wrong reading... it's ok now, no more artisan errors.
Thank you for you effort.

**Comment by paul-thebaud** [comment]
No problem, feel free if you need anything else :)

**Comment by paul-thebaud** [comment]
PhpUnitGen version 2.0.0 stable released with PHP 8 support.
