### ISSUE TITLE
Avoiding generation of Test class for classes without any public method

### ISSUE THREAD

**Issue by tbondois** [paul-thebaud/phpunitgen-console#7]
For now, phpunitgen create classes when even if nothing is public.

That's make PHPUnit considering the tests as failed

So I suggest throw a warning instead of actually creating Test classes containing no methods to test.

Same for abstract functions, Interfaces... Their generation actually throw an error. They should just be ignored, in my opinion

**Comment by paul-thebaud** [comment]
Hi,

That's a great idea, thanks a lot.

After investigation, I think this issue will also affect the [phpunitgen/core](https://github.com/paul-thebaud/phpunitgen-core) package.

To solve this, we should check if a test generator can generate tests for a given class before calling the `generate` method on the console application (and trigger a warning if it cannot). `canGenerate` method should also return false if there is no method to test on the core package (because of exclusion or non public methods).

I'll try to work on this as soon as possible and release it on 1.x.x and 2.x.x.

**Comment by tbondois** [comment]
Hi Paul,

I'm glad you found my suggestion relevant.
For my part this would make the automatic implementation of your lib on my projects way more convenient, so I'm really looking forward to it ;)

I really like your project by the way, even if there are still many things that can be added in generators (for exemple, generating method calls on mock objects, like `$this->myMockObject->expects ($this->once ())->method ('getName' )->willReturn('Santa Claus');`, would be awesome !), the code is pretty and clean. Continue with the good job !

And Merry Xmas

**Comment by paul-thebaud** [comment]
Hi Thomas,

Thanks, this might take me some time to release this, sorry, because I've found a new bug on the V2 beta today 😔

I'll link my advancement here using PR, etc.

About other features proposal, you can create new issues with detailed feature request. You might also propose PR on core and console packages if you'd want.

Merry Christmas to you 🎉

**Comment by paul-thebaud** [comment]
Related PR for releases on console package:

- `1.x.x`: #8
- `2.x.x`: #9

**Comment by paul-thebaud** [comment]
Hi @tbondois,

This new feature is now release on core and console packages. Here are the corresponding versions' numbers:

- `phpunitgen/core`: `1.2.0` and `2.0.0-alpha5`
- `phpunitgen/console`: `1.5.0` and `2.0.0-alpha6`

Now, when calling PhpUnitGen on an interface or a class without public methods, this won't generate any corresponding tests class. For interfaces, this will create a warning instead of an error.

As a reminder, when an error is detected by the CLI, this will results in a `100` return code. For warnings, the code is `101`. For full success (no error or warning), the code is `0`.

You can close the issue if you think it fix the initial problem (I'll close it in a few days without an answer from you).

If you have any other issue, feel free to open a new one or submit a PR.

**Comment by paul-thebaud** [comment]
Hi @tbondois,
Looks OK, closing. Feel free to reopen if the issue still exist from your point of view.
